### ISSUE TITLE
Raising reputation does not work

### ISSUE THREAD

**Issue by svg2017** [SweptThrone/STReputation#1]
When killing an opponent, even if he has a bad reputation, the reputation still takes away, although it should be increased.

**Comment by SweptThrone** [comment]
I see what I did wrong.
Should be fixed now, but I can't confirm it right now.
Let me know if it's fixed or not.

**Comment by svg2017** [comment]
[ERROR] addons/streputation/lua/autorun/server/st_reputationsystem.lua:30: function arguments expected near '=='
  1. unknown - addons/streputation/lua/autorun/server/st_reputationsystem.lua:0

**Comment by SweptThrone** [comment]
God dammit.
Should be fixed.
